apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fpro-lwdc-query
rules:
- apiGroups:
  - ""
  - "apps"
  - "extensions"
  resources:
  - nodes
  - services
  - configmaps
  - pods
  - deployments
  - endpoints
  - clusters
  verbs:
  - list
  - get