kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fpro-lwdc-rolebinding
  namespace: fpro-icam-app-ns
subjects:
- kind: User
  name: system:serviceaccount:fpro-icam-app-ns:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: fpro-lwdc-query
  apiGroup: rbac.authorization.k8s.io
  