apiVersion: v1
kind: Namespace
metadata:
  name: apro-app-ns
  labels:
    app: apro-application
---
apiVersion: v1
kind: Namespace
metadata:
  name: apro-channel-ns
  labels:
    app: apro-application
---
apiVersion: v1
kind: Namespace
metadata:
  name: apro-subscription-ns
  labels:
    app: apro-application
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: apro
  namespace: apro-subscription-ns
  labels:
    app: apro-application
spec:
  selector:
    matchLabels:
      app: apro-application
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: apro-channel
  namespace: apro-channel-ns
  labels:
    app: apro-application
spec:
  type: Namespace
  pathname: apro-channel-ns
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: apro-subscription
  namespace: apro-subscription-ns
  labels:
    app: apro-application
    test: test1
spec:
  channel: apro-channel-ns/apro-channel
  packageFilter:
    labelSelector:
      matchLabels:
        app: apro-application
  placement:
    placementRef:
      name: apro-placementrule
      kind: PlacementRule
  overrides:
    - clusterName: /
      clusterOverrides:
        - path: metadata.namespace
          value: apro-app-ns
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: apro-placementrule
  namespace: apro-subscription-ns
  labels:
    app: apro-application
spec:
  clusterLabels:
    matchExpressions:
      - key: name
        operator: In
        values:
          - mcm-managed-cp4a-cluster
  clusterReplicas: 1
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: apro-deployable-deployment-frontweb
  namespace: apro-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: apro-application
    subapp: frontweb
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: apro-frontweb
      namespace: apro-app-ns
      labels:
        app: apro-application
        subname: frontweb
    spec:
      selector:
        matchLabels:
          app: apro-application
          subname: frontweb
      replicas: 5
      template:
        metadata:
          labels:
            app: apro-application
            subname: frontweb
        spec:
          containers:
            - name: container-nginx
              image: "gandhicloudlab/cpro-bankweb:latest"
              imagePullPolicy: Always
              ports:
                - name: my-http
                  containerPort: 9030
              resources:
                {}
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: apro-deployable-service-frontweb
  namespace: apro-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: apro-application
    subapp: frontweb
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: apro-frontweb
      namespace: apro-ns
      labels:
        app: apro-application
        subname: frontweb
    spec:
      type: LoadBalancer
      ports:
        - name: my-http
          port: 9090
          targetPort: my-http
      selector:
        app: apro-application
        subname: frontweb
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: apro-deployable-route-frontweb
  namespace: apro-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: apro-application
    subapp: frontweb
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: apro-frontweb
      namespace: apro-ns
      labels:
        app: apro-application
        subname: frontweb
    spec:
      path: /
      to:
        kind: Service
        name: apro-frontweb
        weight: 100
      port:
        targetPort: my-http
---
