apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cpro
  namespace: cpro-subscription-ns
  labels:
    app: cpro-application
spec:
  selector:
    matchLabels:
      app: cpro-application
    # matchExpressions:
    #   - key: app
    #     operator: In
    #     values:
    #       - cpro-application
  componentKinds:
    - group: app.ibm.com
      kind: Subscription